version: '3.7'

x-defaults: &defaults
  env_file: bot.env
  restart: always
  networks:
    - bot

services:
  morpheushelper:
    << : *defaults
    image: pydrocsid/bot
#    image: pydrocsid/bot:develop
    tty: true
    depends_on:
      - db

  db:
    << : *defaults
    image: mariadb
#    image: jsurf/rpi-mariadb
    volumes:
      - './mysql_data:/var/lib/mysql'

networks:
  bot:
